default_config:


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize:
    climate.smart_thermostat:
      scan_interval: 10  # Updates every 10 seconds

logger:
  default: info
  logs:
    custom_components.smart_thermostat: debug
    custom_components.smart_thermostat.climate: debug
    custom_components.smartir: debug
    homeassistant.components.climate: debug
    homeassistant.core: info
  filters:
    ignore_custom_components: []


smartir:
climate:
  - platform: smartir
    name: "Heat pump"
    unique_id: kitchen_heat_pump
    device_code: 2161
    controller_data: remote.hvac_controller
    temperature_sensor: sensor.hvac_controller_temperature
    humidity_sensor: sensor.hvac_controller_humidity
    power_sensor: binary_sensor.ac_power
  - platform: smart_thermostat
    name: "Smart Furnace"
    temperature_sensors:
      - sensor.bedroom_temperature
      - sensor.office_temperature
      - sensor.thermostat_current_temperature
      - sensor.hvac_controller_temperature
    # hvac_entity: climate.thermostat
    hvac_entity: climate.office_ac
    target_temp: 21.0
    min_temp: 19.0
    max_temp: 22.5
    tolerance: 0.5
    minimum_on_time: 5
    maximum_on_time: 15
    off_time: 5

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/mushroom-cards/mushroom.js 