climate:
  - platform: smart_thermostat
    name: "Smart Thermostat"
    temperature_sensors:
      - sensor.bedroom_temperature
      - sensor.office_temperature
      - sensor.thermostat_current_temperature
      - sensor.hvac_controller_temperature
    hvac_entity: climate.thermostat
    target_temp: 21.0
    min_temp: 19.0
    max_temp: 22.5
    tolerance: 0.5
    minimum_on_time: 5
    maximum_on_time: 15
    off_time: 25 

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/mushroom-cards/mushroom.js 